# Generated by Django 5.1.1 on 2024-09-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcarduser',
            old_name='last_edited_by',
            new_name='last_edited_by_userId',
        ),
    ]
