# Generated by Django 5.1.1 on 2024-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='user', max_length=50)),
            ],
        ),
    ]
