# Generated by Django 5.1.1 on 2024-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='xyz', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
