# Generated by Django 5.1.1 on 2024-09-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_rename_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=255)),
                ('projectDesc', models.TextField()),
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('totalPosition', models.IntegerField()),
                ('role', models.CharField(default='user', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
