# Generated by Django 5.1.1 on 2024-09-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0002_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
