# Generated by Django 5.1.1 on 2024-09-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0003_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(max_length=20),
        ),
    ]
