# Generated by Django 5.1.1 on 2024-09-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0005_project_last_updated_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lasteditedByUser',
        ),
    ]
