# Generated by Django 5.1.1 on 2024-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0009_project_last_edited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='last_edited_by',
            new_name='last_edited_by_userId',
        ),
    ]
