# Generated by Django 5.1.1 on 2024-09-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='CEO', max_length=50),
        ),
    ]
