# Generated by Django 5.1.1 on 2024-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercard', '0002_rename_last_edited_by_projectcarduser_last_edited_by_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcarduser',
            name='budget',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectcarduser',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectcarduser',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectcarduser',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
