# Generated by Django 5.1.1 on 2024-09-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0001_initial'),
        ('register', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcard.project')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
