# Generated by Django 5.1.1 on 2024-09-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0004_alter_project_budget'),
        ('register', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lasteditedByUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='edited_projects', to='register.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='register.user'),
        ),
    ]
