# Generated by Django 5.1.1 on 2024-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0007_remove_project_last_updated_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
