# Generated by Django 5.1.1 on 2024-09-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0008_project_last_updated_timestamp'),
        ('register', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_projects', to='register.user'),
        ),
    ]
