# Generated by Django 5.1.1 on 2024-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcard', '0010_rename_last_edited_by_project_last_edited_by_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
